### ISSUE TITLE
Installer generates incorrect production configuration and fails

### ISSUE THREAD

**Issue by Anthirian** [GhostManager/Ghostwriter#328]
**Describe the bug**
The installer generates incorrect production configuration and fails

**To Reproduce**

Follow the [quickstart instructions](https://www.ghostwriter.wiki/getting-started/quickstart#installing-ghostwriter).

```
$ git clone https://github.com/GhostManager/Ghostwriter.git
$ cd Ghostwriter
$ ./ghostwriter-cli install
```

```
$ sudo ./ghostwriter-cli-linux install
[+] Checking status of Docker and the Compose plugin...
[+] The `compose` is not installed, so we'll try the deprecated `docker-compose` script
[+] The `docker-compose` script is installed, so we'll use that instead
[+] Starting production environment installation
[*] Generating new `ghostwriter.crt` and `ghostwriter.key` files
[*] Did not find existing TLS/SSL certs for the Nginx container, so generating them now...
[+] Successfully generated new TLS/SSL certificates
[*] Generating a new `dhparam.pem` file (this could take a few minutes)
[+] Writing DH parameters to /opt/Ghostwriter/ssl/dhparam.pem
Error while attempting to convert service.django.healthcheck.retries to appropriate type: "'3'" is not a valid integer
[-] Error from `docker-compose`: exit status 1
2023/07/18 10:20:48 Error trying to build with production.yml: exit status 1
```

**Expected Behavior**

As shown in the instructions:

> The install command will take care of everything necessary to create a production environment for you. That command performs the following actions:
> - Sets up the default server configuration
> - Generates TLS certificates for the server
> - Builds the Docker containers
> - Creates a default admin user with a randomly generated password

**Screenshots**

**Server Specs:**
 - OS: Ubuntu 20.04 LTS
 - Docker version: 20.10.21, build 20.10.21-0ubuntu1~20.04.2
 - docker-compose version: 1.25.0, build unknown
 - Ghostwriter: latest master

**Additional context**
It looks like the CLI forcefully generates an `.env` file with values that contain quotes, like below.

```HEALTHCHECK_RETRIES='3'```

The docker-compose specs say that this should be an integer, but the quotes are causing it to be interpreted as a string, which causes the error displayed above.

The same happens for many other variables that are expected to be provided as integers. In YAML there is almost never a need to quote values for keys, so the `.env`'s values should probably _all_ be done without quotes. If I remove them myself (using `sed -i -e "s/'//g" .env`) and check how docker-compose parses the configuration, I get different errors:

```
$ docker-compose -f production.yml config
ERROR: The Compose file './production.yml' is invalid because:
services.django.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
services.graphql_engine.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
services.nginx.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
services.postgres.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
services.queue.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
services.redis.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
```

This part can be solved by bumping the `version` key in the `production.yaml` to at least `3.4`, because from this version onwards the `start_period` key is available.

https://docs.docker.com/compose/compose-file/05-services/#healthcheck

Once we solve all these issues, the compose file is parsed correctly:

```yaml
$ docker-compose -f production.yml config
services:
  django:
    build:
      context: /opt/Ghostwriter
      dockerfile: ./compose/production/django/Dockerfile
    command: /start
    depends_on:
    - postgres
    - redis
    environment:
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: "false"
      DJANGO_ACCOUNT_EMAIL_VERIFICATION: none
      DJANGO_ADMIN_URL: admin/
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 django nginx host.docker.internal
[...truncated...]
version: '3.4'
volumes:
  production_data: {}
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_staticfiles: {}
```

However, once I run the install command again, all changes are overwritten and the initial error pops up again.

If after my changes I start by using `docker-compose -f production.yml up -d` things seem to build and start okay, but the admin password seems to be invalid.
