### ISSUE TITLE
picture

### ISSUE THREAD

**Issue by sqift** [GhostManager/Ghostwriter#38]
Hello
thx for Ghost
How can I upload a picture in the description?

**Comment by sqift** [comment]
i found it - via "evidence"

**Comment by sqift** [comment]
the uploaded picture is not visible in the evidence

![Capture](https://user-images.githubusercontent.com/52957768/67077554-2afc1f80-f198-11e9-801d-f92c10df7285.PNG)

**Comment by chrismaddalena** [comment]
There are instances where the nginx server may not make files available to Django when using production.yml. Editing production.yml and nginx.conf like this will help:

# production.yml
```
  nginx:
    build: ./compose/production/nginx
    image: ghostwriter_production_nginx
    restart: unless-stopped
    depends_on:
      - django
    volumes:
      - production_staticfiles:/app/staticfiles
     # Added the line below
      - production_data:/app/media
      - ./compose/production/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
```

# nginx.conf
```
        location /media {
            alias /app/media;
        }
```

These changes will be included in an upcoming release. Note that these changes make it so unauthenticated visitors can _theoretically_ view evidence files; however, they would have to know the report's ID number and the name of the evidence file.
