### ISSUE TITLE
CSRF breaks when changing the host:port

### ISSUE THREAD

**Issue by fortbridge** [GhostManager/Ghostwriter#581]
**Describe the bug**
When exposing ports like 8080/4443 on the host the CSRF mitigations breaks everything

**To Reproduce**

in production.yaml change exposed ports on the host to 8080/4443

follow the intructions here:https://www.ghostwriter.wiki/getting-started/quickstart
to set allowhost, trustorigin, NGINX_HOST to "ghostwriter" for example

**Expected Behavior**
I'd expect d still be able to use the app

**Screenshots**
everytime I do a POST I get CSRF errors

**Server Specs:**
 - OS: [e.g., Ubuntu]
 - Docker [e.g., output of `docker --version` and `docker-compose -v`]
 - Ghostwriter [e.g., 2.2.3 or whatever is printed at the bottom of the left-hand sidebar]

**Additional context**

**Comment by chrismaddalena** [comment]
Hey @fortbridge, what exactly did you do to change the ports? The CSRF is all part of Django, and Django/CSRF doesn't look at the port used for the server. What matters is the CSRF token + related traffic makes it to the server.

Also, what are the errors you see? What do the Django and nginx logs show after you make a request?

```
 ./ghostwriter-cli logs nginx
 ./ghostwriter-cli logs django
```

If you want to change the ports used for nginx, you must also update the _nginx.conf_. By default, nginx listens on 80 and 443, so _prodction.yml_ exposes those ports.

**Comment by adrian-rt** [comment]
@chrismaddalena 
these are the logs from the container, it fails the referrer check:
```
INFO:     172.20.0.6:44854 - "GET /accounts/login/?next=/reporting/reports/findings/update/21 HTTP/1.0" 200 OK
WARNING 2025-02-04 15:42:24,314 log 16 128121137470264 Forbidden (Referer checking failed - https://ghostwriter:4443/accounts/login/?next=/reporting/reports/findings/update/21 does not match any trusted origins.): /accounts/login/
INFO:     172.20.0.6:44858 - "POST /accounts/login/ HTTP/1.0" 403 Forbidden
INFO:     172.20.0.6:44866 - "GET /favicon.ico HTTP/1.0" 404 Not Found
```

these are the changes to production.yml:

```
adrian@adrian-Precision-7750:~/Downloads/tools/Ghostwriter$ cat production.yml | grep -i -C 3 4443
      name: ghostwriter_nginx
    ports:
      - "0.0.0.0:8090:80"
      - "0.0.0.0:4443:443"
    environment:
      - NO_PROXY=django,graphql_engine
    healthcheck:

```
